# Generated by Django 3.1.1 on 2024-08-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='truck',
        ),
        migrations.AddField(
            model_name='truck',
            name='permits',
            field=models.ManyToManyField(related_name='trucks', to='projectApp.Permit'),
        ),
    ]
