# Generated by Django 3.1.1 on 2024-07-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_driver_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='last_oil_change_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truck',
            name='total_km_driven',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_km_driven', models.PositiveIntegerField(default=0)),
                ('diesel_consumed', models.PositiveIntegerField(default=0)),
                ('diesel_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('truck_avg', models.FloatField(default=0)),
                ('fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_repair_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.destination')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.driver')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.truck')),
            ],
        ),
    ]
