# Generated by Django 3.1.1 on 2024-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_driver_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='on_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='on_trip',
            field=models.BooleanField(default=False),
        ),
    ]
