# Generated by Django 3.1.1 on 2024-08-15 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_auto_20240815_0434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permit',
            unique_together=set(),
        ),
    ]
