# Generated by Django 3.1.1 on 2024-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_auto_20240815_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_maintenance_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='truck',
            name='token_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_maintenance_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='diesel_consumed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='diesel_price',
            field=models.FloatField(),
        ),
    ]
