# Generated by Django 3.1.1 on 2024-08-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0006_auto_20240815_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='diesel_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
