# Generated by Django 3.1.1 on 2024-08-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_auto_20240815_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
