# Generated by Django 3.1.1 on 2024-08-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_auto_20240815_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='daily_expenses',
            field=models.IntegerField(default=0),
        ),
    ]
